name: ServerDeployment
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NextJs app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          port: 5432

          scripts: |
            cd Projects/elhofaz_frontend
            git pull git@github.com:abdalla-ayman/elhofaz_frontend.git
            npm i
            pm2 restart elhofaz_frontend
            echo 'deployment succeeded'
